# .github/workflows/firebase-hosting.yml
# Deploy to Firebase Hosting when code is pushed to master
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out your code
      - uses: actions/checkout@v4

      # 2️⃣ Ensure a compatible Node version is first in $PATH
      - name: Use Node.js 20 (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # optional – speeds up npm ci

      # 3️⃣ Install deps and build
      - run: |
          npm ci
          npm run build

      # 4️⃣ Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NOVACOVICI_PORTFOLIO }}
          channelId: live # production
          projectId: novacovici-portfolio
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels # keep if you rely on preview channels
